# Generated by Django 6.0.6 on 2026-07-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_sold_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
