# Generated by Django 6.1 on 2026-08-26 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_sku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('restock_product', 'Can restock products'), ('edit_product', 'Can edit products'), ('product_actions', 'Can perform product actions'), ('display_products', 'Can display products'), ('sold_product', 'Can record sold products')]},
        ),
    ]
