# Generated by Django 6.1 on 2026-08-26 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('restock_product', 'Can restock products'), ('edit_product', 'Can edit products'), ('product_actions', 'Can perform product actions'), ('display_products', 'Can display products'), ('sold_product', 'Can record sold products'), ('sale_history', 'can see sales history')]},
        ),
    ]
